apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: go-webapp
  name: go-webapp
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/go-webapp
spec:
  progressDeadlineSeconds: 600
  replicas: 25
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: go-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: go-webapp
    spec:
      containers:
      - image: gcr.io/edreams-pso-playground/test_go_webapp
        imagePullPolicy: Always
        name: go-webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: STARTUP_DELAY
          value: "10"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
